name: practice01
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # State Management (+DI)
  flutter_bloc: ^9.1.1

  # Utility
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # Routing
  go_router: ^15.1.2

  # UI
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/banners/
