name: practice01
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # State Management (+DI)
  flutter_bloc: ^9.1.1

  # Utility
  json_annotation: ^4.9.0
  equatable: ^2.0.5

  # Routing
  go_router: ^15.1.2

  # UI
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  soft_edge_blur: ^0.1.3
  convex_bottom_bar: ^3.2.0
  flutter_sliding_up_panel: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/banners/

  fonts:
    - family: Debussy
      fonts:
        - asset: assets/fonts/debussy.ttf

    - family: Paperlogy
      fonts:
        - asset: assets/fonts/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Paperlogy-6SemiBold.ttf
          weight: 600

